version: 2
updates:
  # Vérifie les mises à jour des bibliothèques Java (Gradle)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # Vérifie les mises à jour des GitHub Actions (ex: checkout@v4)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
